version: '{build}'

skip_tags: true

environment:
  matrix:
    - RUBY_VERSION: 22
    - RUBY_VERSION: 22-x64
    - RUBY_VERSION: 21
    - RUBY_VERSION: 21-x64
    - RUBY_VERSION: 200
    - RUBY_VERSION: 193

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem install bundler
  - bundle install --path=vendor/bundle --retry=3 --jobs=3

cache:
  - vendor/bundle

build: off

before_test:
  - bundle env
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rspec
  - bundle exec ruby -Ilib bin/metric_fu --no-open
